apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api-sample.fullname" . }}
  labels:
    {{- include "rest-api-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: attestation
  selector:
    {{- include "rest-api-sample.selectorLabels" . | nindent 4 }}
